version: "3.8"
services:
  cassandra:
    image: cassandra:4
    container_name: thehive-cassandra
    restart: unless-stopped
    environment:
      CASSANDRA_CLUSTER_NAME: thehive
    volumes:
      - cassandra-data:/var/lib/cassandra

  elasticsearch:
    image: elasticsearch:7.17.12
    container_name: thehive-elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  thehive:
    image: strangebee/thehive:5.2
    container_name: thehive
    restart: unless-stopped
    env_file: ../.env
    depends_on:
      - cassandra
      - elasticsearch
    ports:
      - "9000:9000"
    environment:
      - JVM_OPTS=-Xms512m -Xmx512m
    command:
      - --secret
      - "${THEHIVE_SECRET}"
      - "--cql-hostnames"
      - "cassandra"
      - "--index-backend"
      - "elasticsearch"
      - "--es-hostnames"
      - "elasticsearch"

volumes:
  cassandra-data:
  elasticsearch-data:
